# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 05:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_auto_20170804_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='members_name',
            new_name='member_name',
        ),
    ]
